GET http://localhost:3000/users

###
POST http://localhost:8000/register
Content-Type: application/json

{
            "first_name" : "aku",
            "last_name": "user4",
            "job_id" : "1",
            "email" : "user4@gmail.com",
            "password":  "user1234",
            "re_password": "user1234",
            "phone":"089799887766",
            "gender":"laki-laki",
            "secret_number":"987152"
}

###
POST http://localhost:8000/login
Content-Type: application/json

{
    "email":"user4@gmail.com",
    "password":"user1234"
}

###
GET http://localhost:8000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImZpcnN0X25hbWUiOiJha3UiLCJlbWFpbCI6InVzZXI0QGdtYWlsLmNvbSIsImlhdCI6MTY3NTEyMDU5OCwiZXhwIjoxNjc1MTIwNjEzfQ.RFVN6X-OE2D-P-Riv9NEJ24bTgLjlgaZBrjHGDANJD8

###
GET http://localhost:8000/token

### 
DELETE  http://localhost:3000/logout

###
GET http://localhost:8000/data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImZpcnN0X25hbWUiOiJha3UiLCJlbWFpbCI6InVzZXI0QGdtYWlsLmNvbSIsImlhdCI6MTY3NTEyMDY1MywiZXhwIjoxNjc1MTIwNjY4fQ.Ei4dQnjx049epoXQtDewzEC2Jdt2n9wNShVBB3POGYE

###
POST http://localhost:8000/data
{
   "location":"surabaya",
            "floor":"3",
            "rack":"A.15.07",
            "hostname":"SBRK03JSBKJS",
            "capacity":"100g",
            "brand":"huawei",
            "type":"catalys",
            "serial_number":"dhviuubnod",
            "functions":"server",
            "category":"server",
            "group":"IT",
            "status":"on",
            "created_by":"1"
}