GET http://localhost:3000/users

###
POST http://localhost:8000/register
Content-Type: application/json

{
    "first_name" : "aku",
    "last_name": "user4",
    "job_id" : "1",
    "email" : "user4@gmail.com",
    "password":  "user1234",
    "re_password": "user1234",
    "phone":"089799887766",
    "gender":"laki-laki",
    "secret_number":"987152"
}

###
POST http://localhost:8000/v1/api/login
Content-Type: application/json

{
    "email":"firman.fp123@gmail.com",
    "password":"123456"
}

###
GET http://localhost:8000/v1/api/users


###
GET http://localhost:8000/v1/api/token

### 
DELETE  http://localhost:3000/logout

###
GET http://localhost:8000/v1/api/data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImZpcnN0X25hbWUiOiJGaXJtYW4iLCJlbWFpbCI6ImZpcm1hbi5mcDEyM0BnbWFpbC5jb20iLCJpYXQiOjE2NzUyMDcxNzksImV4cCI6MTY3NTIwNzE5OX0.xayBupYMT90uJedYa6Gt0_Zt9NcxTu08pU1o7skpxkA


###
POST http://localhost:8000/v1/api/data

{
            "location":"surabaya",
            "floor":3,
            "rack":"A.15.07",
            "hostname":"SBRK03JSBKJS",
            "capacity":"100g",
            "brand":"huawei",
            "type":"catalys",
            "serial_number":"dhviuubnod",
            "functions":"server",
            "category":"server",
            "group":"IT",
            "status":"on",
            "created_by":"CP"
}