GET http://localhost:3000/users

###
POST http://localhost:3000/register
Content-Type: application/json

{
            "first_name" : "aku",
            "last_name": "user4",
            "jobid" : "1",
            "email" : "user4@gmail.com",
            "password":  "user1234",
            "re_password": "user1234",
            "phone":"089799887766",
            "gender":"laki-laki",
            "secret_number":"987152"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"user3@gmail.com",
    "password":"user1234"
}

###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImZpcnN0X25hbWUiOiJha3UiLCJlbWFpbCI6InVzZXIzQGdtYWlsLmNvbSIsImlhdCI6MTY3NDcwNjc4NywiZXhwIjoxNjc0NzA2ODA3fQ.2C-y-NUKvVYJ_fufQzslc9Y0tCoi8QAXvhjMs-lE9sc


###
GET http://localhost:3000/token

### 
DELETE  http://localhost:3000/logout